### ISSUE TITLE
Request for Spark! Tech Resources for Sharing Decision App

### ISSUE THREAD

**Issue by MattAS** [BU-Spark/se-shared-decision-making#2]
- Names + emails of all team members who need access:
 - Agadel: agedel@bu.edu
 - Junia: Jjanvier@bu.edu
 - Xicheng: xl88@bu.edu
 
 - Firebase Project
 - The firebase project will be used to host the website, implement firebase authentication and use firestore for user data.
 - Project due date: Dec 12

**Comment by IanSaucy** [comment]
Done! https://console.firebase.google.com/project/se-shared-decision-making

**Comment by IanSaucy** [comment]
once access has been confirmed. Just close this issue.

**Comment by IanSaucy** [comment]
Bump

**Comment by Agedel** [comment]
I was wrong. 
![image](https://user-images.githubusercontent.com/36602538/201755690-dd8b6c3a-09f6-4218-822e-a5d541e88921.png)

**Comment by IanSaucy** [comment]
Give it a try now. I have created DB for you

**Comment by IanSaucy** [comment]
bump

**Comment by IanSaucy** [comment]
Closing due to non-contact
