### ISSUE TITLE
Request for Spark! Tech Resources for Sharing Decision App

### ISSUE THREAD

**Issue by XichengSpencer** [BU-Spark/se-shared-decision-making#5]
Names + emails of all team members who need access

- Agadel: agedel@bu.edu
- Junia: Jjanvier@bu.edu
- Xicheng: xl88@bu.edu

Detailed list of resources needed
- Google Cloud

 A complete description on how you plan to use the resources
 - Need to deploy Strapi( with PostgreSQL db) on Google Cloud

List any relevant course deadlines
 - Project due date: Dec 12

**Comment by IanSaucy** [comment]
It appears you already have access, please see this link.

https://console.cloud.google.com/welcome?project=se-shared-decision-making
